window.WHEEL_IT_RELEASES = {
  "dinero-code": {
    artist: "WiggWard & Poseck Jr.",
    artistBio: "WiggWard, also known as Bop Dymond, is a Jamaican recording artist working in modern dancehall. Poseck Jr. is a Spanish Latin and urban artist with releases including “Madrid,” “GITANIKA,” “Dinero Code” and the 2026 EP “Autentico Roneo de Barrio Vol. 1.” Their pairing makes “Dinero Code” a Jamaica–Spain collaboration rather than a joint act.",
    genre: "Modern Dancehall / Latin Urban",
    style: "Jamaican–Spanish crossover",
    released: "October 22, 2025",
    duration: "2:33",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica / Spain",
    language: "English / Jamaican Patois / Spanish",
    copyright: "℗ 2025 Wheel It! Records",
    description: "WiggWard and Poseck Jr. connect Jamaica and Spain on “Dinero Code,” a compact crossover built around ambition, money-minded focus and street-level confidence.",
    story: "The record brings together two separate artists and scenes: WiggWard’s Jamaican dancehall identity and Poseck Jr.’s Spanish urban catalogue. That contrast gives the release an international character while retaining a direct, club-ready structure.",
    platforms: {apple: "https://music.apple.com/jm/album/dinero-code-single/1846468509", amazon: "https://music.amazon.co.jp/albums/B0FWH7J1D1"},
    credits: [["Primary Artist", "WiggWard (Bop Dymond)"], ["Primary Artist", "Poseck Jr."], ["Record Label", "Wheel It! Records"]]
  },
  "stadaday-in-love": {
    artist: "Stadaday",
    artistBio: "Stadaday is a Jamaican recording artist working in a melodic reggae and contemporary Caribbean lane. Public information remains limited, but his recorded work presents him as a vocalist drawn to relationship-centred writing and direct emotional delivery.",
    genre: "Dancehall / Reggae",
    style: "Melodic Caribbean",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    description: "“In Love” presents Stadaday in a warm, relationship-driven setting, centring romantic commitment and emotional openness within a contemporary Jamaican production.",
    story: "The release favours melody and intimacy over aggression, allowing Stadaday’s vocal performance to carry a direct declaration of affection and give the record an accessible lovers-oriented character.",
    credits: [["Primary Artist", "Stadaday"], ["Record Label", "Wheel It! Records"]]
  },
  "halfway": {
    artist: "Ah-Drianna & The Grei Show",
    artistBio: "Ah-Drianna, born Adrianna Grenade in San Fernando, Trinidad and Tobago, is an R&B and soul artist who developed her recording career after moving to Jamaica. Singing from childhood, she draws on R&B, soul and Caribbean influence, with a catalogue that includes “Bullseye,” “Infatuated,” “Adrijuana,” “Anxiety,” “133 Degrees,” “Tragedy” and “Halfway.”",
    genre: "R&B / Soul",
    style: "Alternative Caribbean R&B",
    released: "August 22, 2025",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica / Trinidad and Tobago",
    language: "English",
    copyright: "℗ 2025 Wheel It! Records",
    description: "“Halfway” brings Ah-Drianna and The Grei Show together for an emotionally direct R&B single about commitment, distance and the limits of uneven effort.",
    story: "Built around Ah-Drianna’s introspective writing and silky vocal tone, the song balances vulnerability with self-respect while The Grei Show supports the record’s understated Caribbean atmosphere.",
    platforms: {apple: "https://music.apple.com/us/artist/ah-drianna/1491370825", spotify: "https://open.spotify.com/artist/4TL9bFCkMgosm2zEO3Zxr9"},
    credits: [["Primary Artists", "Ah-Drianna & The Grei Show"], ["Record Label", "Wheel It! Records"]]
  },
  "be-a-star": {
    artist: "Lady Melody",
    artistBio: "Lady Melody is a Jamaican recording artist introduced through “Me a Star,” her first commercial release. With no earlier public catalogue to lean on, the single serves as her formal introduction: a melodic, self-affirming performance built around confidence, ambition and the declaration of a new artistic identity.",
    genre: "Dancehall / Reggae",
    style: "Inspirational Caribbean",
    type: "Debut Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    description: "“Me a Star” is Lady Melody’s debut statement of confidence, identity and determination.",
    story: "Rather than presenting an established catalogue, the release captures the beginning of one. Lady Melody uses her first official single to announce herself with a forward-looking message centred on self-belief and artistic ambition.",
    credits: [["Primary Artist", "Lady Melody"], ["Debut Commercial Release", "Me a Star"], ["Record Label", "Wheel It! Records"]]
  },
  "overflowing": {
    artist: "StillVillN",
    artistBio: "StillVillN is a Jamaican artist whose catalogue moves across reggae, modern dancehall and melodic Caribbean music. His releases include the album “Felt” and singles such as “Real Eyes,” “Uppercut,” “Change Yuh Reality,” “Success,” “Everywhere I Go,” “blaze” and “Overflowing,” showing a consistent focus on resilience, growth and lived experience.",
    genre: "Reggae",
    style: "Contemporary Jamaican reggae",
    released: "August 1, 2025",
    duration: "2:39",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    copyright: "℗© 2025 Wheel It! Records",
    description: "“Overflowing” places StillVillN in a melodic reggae setting shaped by abundance, emotional intensity and forward momentum.",
    story: "The song presents StillVillN as a confident, expressive lead voice, using a concise arrangement to turn the idea of overflowing energy and feeling into a polished modern reggae single.",
    platforms: {apple: "https://music.apple.com/ca/artist/stillvilln/1493607174", amazon: "https://music.amazon.com/albums/B0FJ6XSFXF"},
    credits: [["Primary Artist", "StillVillN"], ["Record Label", "Wheel It! Records"]]
  },
  "jah-by-my-side": {
    artist: "Whatatamtam",
    artistBio: "Whatatamtam, also known as “Sweet Sweet Water,” is a Jamaican reggae and dancehall recording artist, dancer and live performer. She has described her sound as open to jazz, hip-hop, R&B, alternative, pop and rock, while her public journey has included competitions, stage performances, social-media content and independent releases beginning with “Island Girl” in 2022.",
    genre: "Reggae",
    style: "Spiritual / Conscious Reggae",
    released: "March 28, 2025",
    duration: "2 minutes",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    copyright: "℗ 2025 Wheel It! Records",
    description: "“Jah by My Side” is a faith-centred reggae single focused on spiritual protection, resilience and confidence through belief.",
    story: "The song continues reggae’s tradition of personal testimony, placing Jah at the centre of the artist’s strength, direction and moral grounding while reflecting Whatatamtam’s positive and performance-led identity.",
    platforms: {apple: "https://music.apple.com/jp/album/jah-by-my-side-single/1802766528", amazon: "https://music.amazon.com.au/artists/B09R3Z3NCY/whatatamtam"},
    credits: [["Primary Artist", "Whatatamtam"], ["Also Known As", "Sweet Sweet Water"], ["Record Label", "Wheel It! Records"]]
  },
  "its-you": {
    artist: "Yungg Muta",
    artistBio: "Yungg Muta, born Chafari Mutabaruka Campbell, is a Jamaican reggae and dancehall artist and the grandson of dub poet, broadcaster and cultural figure Mutabaruka. He is also the grandson of veteran music producer Charles Campbell. Raised around music and live performance, he has built his own catalogue through songs including “Thank You Jah,” “Miss Intangible,” “Love Talk,” “H.I.M.” and “It’s You,” with a style grounded in roots, consciousness, upliftment and personal experience.",
    genre: "Reggae / Modern Dancehall",
    style: "Melodic conscious Caribbean",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    description: "“It’s You” places Yungg Muta in an intimate melodic setting, centring romantic focus and direct emotional expression while retaining the warmth of contemporary Jamaican music.",
    story: "The song expands Yungg Muta’s catalogue beyond strictly conscious themes, allowing him to foreground tenderness and personal connection while remaining rooted in the musical foundation and cultural awareness associated with his family legacy.",
    credits: [["Primary Artist", "Yungg Muta"], ["Given Name", "Chafari Mutabaruka Campbell"], ["Record Label", "Wheel It! Records"]]
  },
  "dancehall-stylee": {
    artist: "Swnkah & Sugar Minott",
    artistBio: "Swnkah, born Candice Minott, is a Jamaican recording artist and the daughter of reggae and dancehall pioneer Sugar Minott and music-industry executive Maxine Stowe. Her catalogue includes “Loosen Up,” “Palm Trees,” “Hotgirl,” “Cash Out” and the RZA collaboration “Why Why Why.” Through “Dancehall Stylee,” she extends her father’s legacy while asserting her own voice across reggae, dancehall and hip-hop-influenced music.",
    genre: "Modern Dancehall",
    style: "Dancehall heritage / contemporary reggae",
    released: "May 20, 2025",
    duration: "3:03",
    bpm: "144",
    language: "English / Jamaican Patois",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    copyright: "℗ 2025 Wheel It! Records",
    description: "Swnkah honours her father Sugar Minott and the living spirit of Jamaican dancehall on a cross-generational record that connects heritage with a new era.",
    story: "“Dancehall Stylee” is presented not as a conventional remake but as a spiritual continuation. Swnkah uses new lyrics and contemporary production to honour both parents, reconnect with foundational dancehall and carry that legacy into her own catalogue.",
    platforms: {apple: "https://music.apple.com/us/album/dancehall-stylee-single/1811688370", amazon: "https://music.amazon.com/tracks/B0F72Q9ZD9"},
    credits: [["Performing Artists", "Swnkah & Lincoln “Sugar” Minott"], ["Songwriters", "Lincoln “Sugar” Minott & Candice Minott"], ["Producer", "The Grei Show"], ["Synthesizer", "The Grei Show"], ["Executive Producer", "Maxine Stowe"], ["Record Label", "Wheel It! Records"]]
  },
  "skill-riddim-vol-1": {
    artist: "1Prayz, Brown Chops, Jco Don & Prezidential",
    artistBio: "Skill Riddim, Vol. 1 brings together four emerging Jamaican voices—1Prayz, Brown Chops, Jco Don and Prezidential—on one shared dancehall production, giving each artist space to approach the riddim from a different lyrical and performance angle.",
    genre: "Modern Dancehall",
    style: "Riddim compilation",
    released: "June 21, 2024",
    duration: "12 minutes",
    type: "Riddim Project · 5 Tracks",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    copyright: "℗ 2024 Wheel It! Records",
    description: "A five-track riddim project featuring 1Prayz, Brown Chops, Jco Don and Prezidential across a shared Wheel It! Records production.",
    story: "The project follows the classic Jamaican riddim format: multiple artists, one instrumental foundation and distinct songs shaped by contrasting flows, themes and vocal characters.",
    platforms: {amazon: "https://music.amazon.com/albums/B0DCF4LQ21"},
    tracklist: ["Isolation — 1Prayz — 2:27", "Vladamir — Brown Chops — 2:26", "Hit Sound — Jco Don — 2:27", "Money — Prezidential — 2:29", "Skill Riddim, Vol. 1 — 1Prayz, Brown Chops, Jco Don & Prezidential — 2:53"],
    credits: [["Featured Artists", "1Prayz, Brown Chops, Jco Don & Prezidential"], ["Record Label", "Wheel It! Records"]]
  },
  "cash-out": {
    artist: "Swnkah",
    artistBio: "Swnkah, born Candice Minott, is a Jamaican recording artist and the daughter of Sugar Minott and Maxine Stowe. Her work crosses reggae, dancehall and hip-hop-influenced music, with releases including “Loosen Up,” “Palm Trees,” “Hotgirl,” “Why Why Why” with RZA, “Dancehall Stylee” and “Cash Out.”",
    genre: "Hip-Hop/Rap",
    released: "June 22, 2021",
    duration: "2 minutes",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    copyright: "℗ 2021 Wheel It! Records",
    description: "“Cash Out” is a concise solo statement from Swnkah, pairing her Jamaican delivery with a rap-oriented release format.",
    story: "The song leans into confidence, independence and financial ambition while expanding Swnkah’s catalogue beyond strictly reggae and dancehall framing.",
    platforms: {apple: "https://music.apple.com/us/album/cash-out-single/1571833861"},
    credits: [["Primary Artist", "Swnkah"], ["Given Name", "Candice Minott"], ["Record Label", "Wheel It! Records"]]
  },
  "steaming": {
    artist: "Karbon D Hardone",
    artistBio: "Karbon D Hardone, also styled Karbon D Hard 1, is a Kingston-born Jamaican roots-reggae artist raised in Broadleaf, Manchester. A Rastafarian singer focused on substance over hype, identity, resilience and spiritual elevation, he began writing as a teenager and later became associated with Yaadcore’s 12 Yaad Records. His catalogue includes “Highgrade Maka,” “Fully Awake,” “She’s Mine,” “Hesitate,” “Jamaica” and “Steaming.”",
    genre: "Reggae",
    style: "Contemporary roots reggae",
    released: "March 28, 2025",
    duration: "2:38",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    copyright: "℗ 2025 Wheel It! Records",
    description: "Karbon D Hardone delivers “Steaming,” a concise roots-reggae single carrying his spiritually grounded, modern Jamaican identity.",
    story: "The release fits Karbon’s broader approach: foundation-minded reggae delivered with contemporary edge, lyrical purpose and a focus on resilience rather than spectacle.",
    platforms: {apple: "https://music.apple.com/us/album/steaming-single/1800345903", amazon: "https://music.amazon.com.au/albums/B0DZG93RYR"},
    credits: [["Primary Artist", "Karbon D Hardone"], ["Also Styled As", "Karbon D Hard 1"], ["Record Label", "Wheel It! Records"]]
  }
};