window.WHEEL_IT_RELEASES = {
  "dinero-code": {
    artist: "WiggWard & Poseck Jr.",
    artistBio: "WiggWard and Poseck Jr. are Jamaican dancehall artists working in the contemporary modern-dancehall lane, pairing melodic delivery with street-focused writing and compact digital-era releases.",
    genre: "Modern Dancehall",
    released: "October 22, 2025",
    duration: "2:33",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    copyright: "℗ 2025 Wheel It! Records",
    description: "WiggWard and Poseck Jr. join forces on “Dinero Code,” a concise modern-dancehall record built around ambition, momentum and the codes surrounding money and survival.",
    story: "The collaboration places both artists at the centre of the record, with Wheel It! Records providing the release platform and production framework for a focused, contemporary dancehall statement.",
    platforms: {
      apple: "https://music.apple.com/jm/album/dinero-code-single/1846468509",
      amazon: "https://music.amazon.co.jp/albums/B0FWH7J1D1"
    },
    credits: [["Primary Artists", "WiggWard & Poseck Jr."], ["Record Label", "Wheel It! Records"]]
  },
  "stadaday-in-love": {
    artist: "Stadaday",
    artistBio: "Stadaday is a Jamaican recording artist working within a contemporary Caribbean sound, using melody and direct songwriting to frame personal and relationship-centred themes.",
    genre: "Dancehall / Reggae",
    style: "Melodic Caribbean",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    description: "“In Love” presents Stadaday in a melodic, relationship-driven setting, centring emotion and romantic commitment within a contemporary Jamaican production.",
    story: "The record focuses on Stadaday’s vocal performance and the emotional pull of being fully invested in a relationship, giving the release a warmer and more intimate tone than a typical hard-edged dancehall single.",
    credits: [["Primary Artist", "Stadaday"], ["Record Label", "Wheel It! Records"]]
  },
  "halfway": {
    artist: "Ah-Drianna",
    artistBio: "Ah-Drianna is a Jamaican female recording artist whose work draws on contemporary dancehall, reggae and melodic Caribbean influences.",
    genre: "Dancehall / Reggae",
    style: "Contemporary Caribbean",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    description: "“Half Way” places Ah-Drianna at the centre of an emotionally direct Caribbean single about commitment, distance and the limits of meeting someone halfway.",
    story: "The release is built around Ah-Drianna’s perspective, presenting a relationship narrative that balances vulnerability with self-respect and clear personal boundaries.",
    credits: [["Primary Artist", "Ah-Drianna"], ["Record Label", "Wheel It! Records"]]
  },
  "be-a-star": {
    artist: "Lady Melody",
    artistBio: "Lady Melody is a Jamaican recording artist whose name reflects a vocal-led approach rooted in melody, dancehall and reggae performance.",
    genre: "Dancehall / Reggae",
    style: "Inspirational Caribbean",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    description: "“Me a Star” is an aspirational statement from Lady Melody, built around confidence, identity and the determination to claim her place in music.",
    story: "The song frames Lady Melody as the central character in her own rise, combining self-belief with a forward-looking message suited to audiences drawn to motivational dancehall and reggae records.",
    credits: [["Primary Artist", "Lady Melody"], ["Record Label", "Wheel It! Records"]]
  },
  "overflowing": {
    artist: "Stillvilln",
    artistBio: "Stillvilln is a Jamaican recording artist operating in the modern dancehall and reggae space, with a style shaped by contemporary Caribbean rhythm and melodic delivery.",
    genre: "Dancehall / Reggae",
    style: "Modern Caribbean",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    description: "“Overflowing” showcases Stillvilln in a modern Caribbean setting, using a title and performance built around abundance, momentum and emotional intensity.",
    story: "The release presents Stillvilln as the focal voice, pairing a contemporary Jamaican sound with an expansive theme that can be read through love, energy or personal elevation.",
    credits: [["Primary Artist", "Stillvilln"], ["Record Label", "Wheel It! Records"]]
  },
  "jah-by-my-side": {
    artist: "Whatatamtam",
    artistBio: "Whatatamtam is a Jamaican recording artist whose work draws from reggae’s spiritual language and dancehall’s direct vocal tradition.",
    genre: "Reggae",
    style: "Spiritual / Conscious Reggae",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    description: "“Jah by My Side” is a faith-centred reggae release from Whatatamtam, focused on spiritual protection, resilience and confidence through belief.",
    story: "The song places Jah at the centre of the artist’s strength and direction, continuing reggae’s long tradition of using personal testimony to express faith, endurance and moral grounding.",
    credits: [["Primary Artist", "Whatatamtam"], ["Record Label", "Wheel It! Records"]]
  },
  "its-you": {
    artist: "Yung Muta",
    artistBio: "Yung Muta is a Jamaican recording artist working across contemporary dancehall, reggae and melodic Caribbean music.",
    genre: "Dancehall / Reggae",
    style: "Melodic Caribbean",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    description: "“It’s You” puts Yung Muta in a melodic and personal setting, centring the record on romantic focus and direct emotional expression.",
    story: "The release is built around a clear declaration to one person, giving Yung Muta room to deliver a more intimate performance within a contemporary Jamaican framework.",
    credits: [["Primary Artist", "Yung Muta"], ["Record Label", "Wheel It! Records"]]
  },
  "dancehall-stylee": {
    artist: "Swnkah & Sugar Minott",
    artistBio: "Swnkah is a Jamaican recording artist continuing the musical legacy of her father, reggae and dancehall pioneer Sugar Minott. Sugar Minott was a foundational singer, songwriter and producer whose work helped shape lovers rock, roots reggae and the sound-system culture that fed modern dancehall.",
    genre: "Modern Dancehall",
    style: "Dancehall heritage / contemporary reggae",
    released: "May 20, 2025",
    duration: "3:03",
    bpm: "144",
    language: "English / Jamaican Patois",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    copyright: "℗ 2025 Wheel It! Records",
    description: "Swnkah honours her father Sugar Minott and the living spirit of Jamaican dancehall on a cross-generational record that connects heritage with a new era.",
    story: "“Dancehall Stylee” centres Swnkah’s voice while drawing directly from Sugar Minott’s legacy. The release works as both a family tribute and a forward-looking dancehall single, linking foundational Jamaican music with contemporary production.",
    platforms: {
      apple: "https://music.apple.com/us/album/dancehall-stylee-single/1811688370",
      amazon: "https://music.amazon.com/tracks/B0F72Q9ZD9"
    },
    credits: [["Performing Artists", "Swnkah & Lincoln “Sugar” Minott"], ["Songwriters", "Lincoln “Sugar” Minott & Candice Minott"], ["Producer", "The Grei Show"], ["Synthesizer", "The Grei Show"], ["Executive Producer", "Maxine Stowe"], ["Record Label", "Wheel It! Records"]]
  },
  "skill-riddim-vol-1": {
    artist: "1Prayz, Brown Chops, Jco Don & Prezidential",
    artistBio: "Skill Riddim, Vol. 1 brings together four emerging Jamaican voices—1Prayz, Brown Chops, Jco Don and Prezidential—on one shared dancehall production, allowing each artist to approach the same musical foundation from a different lyrical and performance angle.",
    genre: "Modern Dancehall",
    style: "Riddim compilation",
    released: "June 21, 2024",
    duration: "12 minutes",
    type: "Riddim Project · 5 Tracks",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    copyright: "℗ 2024 Wheel It! Records",
    description: "A five-track riddim project featuring 1Prayz, Brown Chops, Jco Don and Prezidential across a shared Wheel It! Records production.",
    story: "The project follows the classic Jamaican riddim format: multiple artists, one instrumental foundation, distinct songs and identities. The result is a compact showcase of contrasting flows, themes and vocal characters.",
    platforms: {amazon: "https://music.amazon.com/albums/B0DCF4LQ21"},
    tracklist: ["Isolation — 1Prayz — 2:27", "Vladamir — Brown Chops — 2:26", "Hit Sound — Jco Don — 2:27", "Money — Prezidential — 2:29", "Skill Riddim, Vol. 1 — 1Prayz, Brown Chops, Jco Don & Prezidential — 2:53"],
    credits: [["Featured Artists", "1Prayz, Brown Chops, Jco Don & Prezidential"], ["Record Label", "Wheel It! Records"]]
  },
  "cash-out": {
    artist: "Swnkah",
    artistBio: "Swnkah is a Jamaican recording artist whose work bridges her family’s reggae heritage with a contemporary approach to dancehall, rap and melodic Caribbean music.",
    genre: "Hip-Hop/Rap",
    released: "June 22, 2021",
    duration: "2 minutes",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    copyright: "℗ 2021 Wheel It! Records",
    description: "“Cash Out” is a concise solo statement from Swnkah, pairing her Jamaican delivery with a rap-oriented release format.",
    story: "The song presents Swnkah as the central voice, leaning into confidence, independence and financial ambition while retaining a distinctly Jamaican rhythmic identity.",
    platforms: {apple: "https://music.apple.com/us/album/cash-out-single/1571833861"},
    credits: [["Primary Artist", "Swnkah"], ["Record Label", "Wheel It! Records"]]
  },
  "steaming": {
    artist: "Karbon",
    artistBio: "Karbon is a reggae recording artist with a contemporary Jamaican sound and a catalogue that includes singles such as “Steaming.”",
    genre: "Reggae",
    released: "March 28, 2025",
    duration: "2:38",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    copyright: "℗ 2025 Wheel It! Records",
    description: "Karbon delivers “Steaming,” a compact reggae single released through Wheel It! Records in 2025.",
    story: "The release positions Karbon at the centre of a concise, modern reggae presentation designed for streaming, radio and selector circulation.",
    platforms: {
      apple: "https://music.apple.com/us/album/steaming-single/1800345903",
      amazon: "https://music.amazon.com.au/albums/B0DZG93RYR"
    },
    credits: [["Primary Artist", "Karbon"], ["Record Label", "Wheel It! Records"]]
  }
};