window.WHEEL_IT_RELEASES = {
  "dinero-code": {
    artist: "WiggWard & Poseck Jr.",
    artistBio: "WiggWard and Poseck Jr. are contemporary Jamaican dancehall artists whose collaboration places melodic delivery and street-focused writing inside a compact modern-dancehall format.",
    genre: "Modern Dancehall",
    released: "October 22, 2025",
    duration: "2:33",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    copyright: "℗ 2025 Wheel It! Records",
    description: "WiggWard and Poseck Jr. join forces on “Dinero Code,” a focused modern-dancehall record built around ambition, momentum and survival-minded confidence.",
    story: "The collaboration gives both artists equal space, with a concise arrangement designed for immediate impact across streaming, radio and selector circulation.",
    platforms: {apple: "https://music.apple.com/jm/album/dinero-code-single/1846468509", amazon: "https://music.amazon.co.jp/albums/B0FWH7J1D1"},
    credits: [["Primary Artists", "WiggWard & Poseck Jr."], ["Record Label", "Wheel It! Records"]]
  },
  "stadaday-in-love": {
    artist: "Stadaday",
    artistBio: "Stadaday is a Jamaican recording artist with roots in reggae collaboration and a melodic approach suited to relationship-centred material. Public catalogue references place Stadaday among Jamaican vocalists working across reggae and contemporary Caribbean music.",
    genre: "Dancehall / Reggae",
    style: "Melodic Caribbean",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    description: "“In Love” presents Stadaday in a warm, relationship-driven setting, centring romantic commitment and emotional openness within a contemporary Jamaican production.",
    story: "The release favours melody and intimacy over aggression, allowing Stadaday’s vocal performance to carry a direct declaration of affection.",
    credits: [["Primary Artist", "Stadaday"], ["Record Label", "Wheel It! Records"]]
  },
  "halfway": {
    artist: "Ah-Drianna & The Grei Show",
    artistBio: "Ah-Drianna, born Adrianna Grenade in San Fernando, Trinidad and Tobago, is an R&B/soul artist who developed her career in Jamaica. Her music blends silky vocals, emotionally direct songwriting and Caribbean influence, with a catalogue shaped by love, relationships and introspection.",
    genre: "R&B / Soul",
    style: "Alternative Caribbean R&B",
    released: "August 22, 2025",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica / Trinidad and Tobago",
    language: "English",
    copyright: "℗ 2025 Wheel It! Records",
    description: "“Halfway” brings Ah-Drianna and The Grei Show together for an emotionally direct R&B single about commitment, distance and the limits of uneven effort.",
    story: "Built around Ah-Drianna’s introspective writing and vocal restraint, the song balances vulnerability with self-respect while The Grei Show supports the record’s understated Caribbean atmosphere.",
    platforms: {apple: "https://music.apple.com/us/artist/ah-drianna/1491370825", spotify: "https://open.spotify.com/artist/4TL9bFCkMgosm2zEO3Zxr9"},
    credits: [["Primary Artists", "Ah-Drianna & The Grei Show"], ["Record Label", "Wheel It! Records"]]
  },
  "be-a-star": {
    artist: "Lady Melody",
    artistBio: "Lady Melody is a Jamaican recording artist presented here through a vocal-led, motivational dancehall and reggae direction. Her public profile remains emerging, so this release is positioned around the strength of the song and performance rather than unverified biography.",
    genre: "Dancehall / Reggae",
    style: "Inspirational Caribbean",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    description: "“Me a Star” is Lady Melody’s aspirational statement of confidence, identity and determination.",
    story: "The record frames Lady Melody as the central voice in her own rise, translating self-belief into a forward-looking dancehall and reggae anthem.",
    credits: [["Primary Artist", "Lady Melody"], ["Record Label", "Wheel It! Records"]]
  },
  "overflowing": {
    artist: "StillVillN",
    artistBio: "StillVillN is a Jamaican Caribbean artist with releases spanning reggae, modern dancehall and melodic collaborations. His catalogue includes “Greatness,” “Triumphant,” “Vibes Deh,” “Everywhere I Go” and “Overflowing,” reflecting a flexible approach to contemporary Jamaican music.",
    genre: "Reggae",
    style: "Contemporary Jamaican reggae",
    released: "August 1, 2025",
    duration: "2:39",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    copyright: "℗© 2025 Wheel It! Records",
    description: "“Overflowing” places StillVillN in a melodic reggae setting shaped by abundance, emotional intensity and forward momentum.",
    story: "The song presents StillVillN as a confident, expressive lead voice, using a concise arrangement to turn the idea of overflowing energy and feeling into a polished modern reggae single.",
    platforms: {apple: "https://music.apple.com/ca/artist/stillvilln/1493607174", amazon: "https://music.amazon.com/albums/B0FJ6XSFXF"},
    credits: [["Primary Artist", "StillVillN"], ["Record Label", "Wheel It! Records"]]
  },
  "jah-by-my-side": {
    artist: "Whatatamtam",
    artistBio: "Whatatamtam, also known as “Sweet Sweet Water,” is a Jamaican reggae and dancehall artist, live performer and host whose work centres positive, conscious music. Her background includes competitions, regular stage performances and collaborations across Jamaica’s independent reggae community.",
    genre: "Reggae",
    style: "Spiritual / Conscious Reggae",
    released: "March 28, 2025",
    duration: "2 minutes",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    copyright: "℗ 2025 Wheel It! Records",
    description: "“Jah by My Side” is a faith-centred reggae single focused on spiritual protection, resilience and confidence through belief.",
    story: "The song continues reggae’s tradition of personal testimony, placing Jah at the centre of the artist’s strength, direction and moral grounding.",
    platforms: {apple: "https://music.apple.com/jp/album/jah-by-my-side-single/1802766528", amazon: "https://music.amazon.com.au/artists/B09R3Z3NCY/whatatamtam"},
    credits: [["Primary Artist", "Whatatamtam"], ["Record Label", "Wheel It! Records"]]
  },
  "its-you": {
    artist: "Yung Muta",
    artistBio: "Yung Muta is a modern-dancehall artist born February 22, 1997. His music sits within the contemporary Jamaican dancehall space, balancing rhythmic delivery with melodic, relationship-focused material.",
    genre: "Modern Dancehall",
    style: "Melodic Dancehall",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    description: "“It’s You” places Yung Muta in an intimate melodic-dancehall setting, centring romantic focus and direct emotional expression.",
    story: "The song is structured as a clear declaration to one person, giving Yung Muta room to foreground melody and sincerity within a contemporary dancehall framework.",
    platforms: {apple: "https://music.apple.com/ca/artist/yung-muta/1685951207"},
    credits: [["Primary Artist", "Yung Muta"], ["Record Label", "Wheel It! Records"]]
  },
  "dancehall-stylee": {
    artist: "Swnkah & Sugar Minott",
    artistBio: "Swnkah is a Jamaican recording artist continuing the musical legacy of her father, reggae and dancehall pioneer Sugar Minott. Sugar Minott was a foundational singer, songwriter and producer whose work helped shape lovers rock, roots reggae and the sound-system culture that fed modern dancehall.",
    genre: "Modern Dancehall",
    style: "Dancehall heritage / contemporary reggae",
    released: "May 20, 2025",
    duration: "3:03",
    bpm: "144",
    language: "English / Jamaican Patois",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    copyright: "℗ 2025 Wheel It! Records",
    description: "Swnkah honours her father Sugar Minott and the living spirit of Jamaican dancehall on a cross-generational record that connects heritage with a new era.",
    story: "“Dancehall Stylee” centres Swnkah’s voice while drawing directly from Sugar Minott’s legacy, functioning as both a family tribute and a forward-looking dancehall single.",
    platforms: {apple: "https://music.apple.com/us/album/dancehall-stylee-single/1811688370", amazon: "https://music.amazon.com/tracks/B0F72Q9ZD9"},
    credits: [["Performing Artists", "Swnkah & Lincoln “Sugar” Minott"], ["Songwriters", "Lincoln “Sugar” Minott & Candice Minott"], ["Producer", "The Grei Show"], ["Synthesizer", "The Grei Show"], ["Executive Producer", "Maxine Stowe"], ["Record Label", "Wheel It! Records"]]
  },
  "skill-riddim-vol-1": {
    artist: "1Prayz, Brown Chops, Jco Don & Prezidential",
    artistBio: "Skill Riddim, Vol. 1 brings together four emerging Jamaican voices—1Prayz, Brown Chops, Jco Don and Prezidential—on one shared dancehall production, giving each artist space to approach the riddim from a different lyrical and performance angle.",
    genre: "Modern Dancehall",
    style: "Riddim compilation",
    released: "June 21, 2024",
    duration: "12 minutes",
    type: "Riddim Project · 5 Tracks",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    copyright: "℗ 2024 Wheel It! Records",
    description: "A five-track riddim project featuring 1Prayz, Brown Chops, Jco Don and Prezidential across a shared Wheel It! Records production.",
    story: "The project follows the classic Jamaican riddim format: multiple artists, one instrumental foundation and distinct songs shaped by contrasting flows, themes and vocal characters.",
    platforms: {amazon: "https://music.amazon.com/albums/B0DCF4LQ21"},
    tracklist: ["Isolation — 1Prayz — 2:27", "Vladamir — Brown Chops — 2:26", "Hit Sound — Jco Don — 2:27", "Money — Prezidential — 2:29", "Skill Riddim, Vol. 1 — 1Prayz, Brown Chops, Jco Don & Prezidential — 2:53"],
    credits: [["Featured Artists", "1Prayz, Brown Chops, Jco Don & Prezidential"], ["Record Label", "Wheel It! Records"]]
  },
  "cash-out": {
    artist: "Swnkah",
    artistBio: "Swnkah is a Jamaican recording artist whose work bridges her family’s reggae heritage with a contemporary approach to dancehall, rap and melodic Caribbean music.",
    genre: "Hip-Hop/Rap",
    released: "June 22, 2021",
    duration: "2 minutes",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    copyright: "℗ 2021 Wheel It! Records",
    description: "“Cash Out” is a concise solo statement from Swnkah, pairing her Jamaican delivery with a rap-oriented release format.",
    story: "The song leans into confidence, independence and financial ambition while retaining a distinctly Jamaican rhythmic identity.",
    platforms: {apple: "https://music.apple.com/us/album/cash-out-single/1571833861"},
    credits: [["Primary Artist", "Swnkah"], ["Record Label", "Wheel It! Records"]]
  },
  "steaming": {
    artist: "Karbon",
    artistBio: "Karbon is a reggae recording artist with a contemporary Jamaican sound and a catalogue that includes singles such as “Steaming.”",
    genre: "Reggae",
    released: "March 28, 2025",
    duration: "2:38",
    type: "Single",
    label: "Wheel It! Records",
    country: "Jamaica",
    language: "English / Jamaican Patois",
    copyright: "℗ 2025 Wheel It! Records",
    description: "Karbon delivers “Steaming,” a compact reggae single released through Wheel It! Records in 2025.",
    story: "The release positions Karbon at the centre of a concise, modern reggae presentation designed for streaming, radio and selector circulation.",
    platforms: {apple: "https://music.apple.com/us/album/steaming-single/1800345903", amazon: "https://music.amazon.com.au/albums/B0DZG93RYR"},
    credits: [["Primary Artist", "Karbon"], ["Record Label", "Wheel It! Records"]]
  }
};