const JSON_HEADERS={'Content-Type':'application/json; charset=utf-8'};
const AVATARS=['🌌','⚡','🔥','🎮','🪐','👾','🎧','🧿'];
const GAME_RULES={
'dreamweaver-oracle':{maxScore:1000000,maxRate:4,grace:25,levelDivisor:4},
'signal-runner':{maxScore:10000000,maxRate:18,grace:60,levelDivisor:10},
'jamaica-run':{maxScore:10000000,maxRate:20,grace:80,levelDivisor:10}
};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...headers}});
function responseHeaders(request,env){const allowed=String(env.ALLOWED_ORIGINS||'https://thegreishow.com,https://www.thegreishow.com').split(',').map(v=>v.trim());const origin=request.headers.get('Origin')||'';return{'Access-Control-Allow-Origin':allowed.includes(origin)?origin:allowed[0],'Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Vary':'Origin','Cache-Control':'no-store'}}
const cleanName=v=>String(v||'Dreamer').replace(/[^a-zA-Z0-9 _-]/g,'').trim().slice(0,18)||'Dreamer';
const cleanCode=v=>String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,12);
const cleanPin=v=>String(v||'').replace(/\D/g,'').slice(0,8);
const number=(v,min,max)=>Number.isFinite(Number(v))&&Number(v)>=min&&Number(v)<=max?Math.floor(Number(v)):null;
async function sha(value){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function pinHash(pin,env){return sha(`${cleanPin(pin)}:${env.SCORE_SALT}`)}
function publicPlayer(p){return{playerCode:p.player_code,name:p.name,avatar:p.avatar,xp:Number(p.xp||0),gamesPlayed:Number(p.games_played||0),joinedAt:p.created_at}}
async function findPlayer(env,code,pin){code=cleanCode(code);pin=cleanPin(pin);if(!code||pin.length<4)return null;return env.ARCADE_DB.prepare('SELECT * FROM players WHERE player_code=? AND pin_hash=?').bind(code,await pinHash(pin,env)).first()}
async function makeCode(env){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(let n=0;n<8;n++){const b=crypto.getRandomValues(new Uint8Array(7)),code='GREI'+[...b].map(x=>a[x%a.length]).join('');if(!await env.ARCADE_DB.prepare('SELECT id FROM players WHERE player_code=?').bind(code).first())return code}throw new Error('code')}
async function profile(request,env){const h=responseHeaders(request,env);if(request.method!=='POST')return json({error:'Method not allowed.'},405,h);const b=await request.json().catch(()=>null);if(!b||!env.SCORE_SALT)return json({error:'Profiles unavailable.'},503,h);if(b.action==='create'){const name=cleanName(b.name),pin=cleanPin(b.pin),avatar=AVATARS.includes(b.avatar)?b.avatar:AVATARS[0];if(name.length<3||pin.length<4)return json({error:'Use a 3–18 character name and a 4–8 digit PIN.'},400,h);const code=await makeCode(env);await env.ARCADE_DB.prepare('INSERT INTO players(player_code,pin_hash,name,avatar)VALUES(?,?,?,?)').bind(code,await pinHash(pin,env),name,avatar).run();return json({ok:true,created:true,player:publicPlayer(await env.ARCADE_DB.prepare('SELECT * FROM players WHERE player_code=?').bind(code).first())},201,h)}if(b.action==='login'){const p=await findPlayer(env,b.playerCode,b.pin);return p?json({ok:true,player:publicPlayer(p)},200,h):json({error:'Player code or PIN is incorrect.'},401,h)}if(b.action==='update'){const p=await findPlayer(env,b.playerCode,b.pin);if(!p)return json({error:'Player code or PIN is incorrect.'},401,h);const name=cleanName(b.name||p.name),avatar=AVATARS.includes(b.avatar)?b.avatar:p.avatar;await env.ARCADE_DB.prepare('UPDATE players SET name=?,avatar=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(name,avatar,p.id).run();await env.ARCADE_DB.prepare('UPDATE scores SET name=? WHERE player_hash=?').bind(name,`account:${p.id}`).run();return json({ok:true,player:publicPlayer(await env.ARCADE_DB.prepare('SELECT * FROM players WHERE id=?').bind(p.id).first())},200,h)}return json({error:'Unknown profile action.'},400,h)}
async function scores(env,game){const r=await env.ARCADE_DB.prepare(`WITH b AS(SELECT id,name,score,level,duration,created_at,player_hash,ROW_NUMBER()OVER(PARTITION BY player_hash ORDER BY score DESC,duration ASC,created_at ASC,id ASC)r FROM scores WHERE game=?)SELECT name,score,level,duration,created_at createdAt FROM b WHERE r=1 ORDER BY score DESC,duration ASC,created_at ASC LIMIT 10`).bind(game).all();return r.results||[]}
async function rank(env,game,score){const r=await env.ARCADE_DB.prepare(`WITH b AS(SELECT player_hash,MAX(score)score FROM scores WHERE game=? GROUP BY player_hash)SELECT COUNT(*)+1 rank FROM b WHERE score>?`).bind(game,score).first();return Number(r?.rank||1)}
async function allow(env,key){await env.ARCADE_DB.prepare("DELETE FROM score_attempts WHERE created_at<=datetime('now','-1 day')").run();const r=await env.ARCADE_DB.prepare("SELECT COUNT(*) total FROM score_attempts WHERE player_hash=? AND created_at>datetime('now','-1 minute')").bind(key).first();if(Number(r?.total||0)>=3)return false;await env.ARCADE_DB.prepare('INSERT INTO score_attempts(player_hash)VALUES(?)').bind(key).run();return true}
async function leaderboard(request,env,url){const h=responseHeaders(request,env);if(request.method==='GET'){const game=url.searchParams.get('game');return GAME_RULES[game]?json({game,scores:await scores(env,game)},200,h):json({error:'Unknown game.'},400,h)}if(request.method!=='POST')return json({error:'Method not allowed.'},405,h);const b=await request.json().catch(()=>null),rules=b&&GAME_RULES[b.game];if(!rules||!env.SCORE_SALT)return json({error:'Invalid submission.'},400,h);const score=number(b.score,0,rules.maxScore),level=number(b.level??1,1,10000),duration=number(b.duration,1,86400);if(score===null||level===null||duration===null)return json({error:'Invalid score data.'},400,h);if(score>duration*rules.maxRate+rules.grace)return json({error:'Score failed plausibility checks.'},422,h);if(b.game==='dreamweaver-oracle'&&level>Math.floor(score/rules.levelDivisor)+3)return json({error:'Level failed plausibility checks.'},422,h);const account=await findPlayer(env,b.playerCode,b.playerPin),ip=request.headers.get('CF-Connecting-IP')||'unknown',key=account?`account:${account.id}`:await sha(`${ip}:${b.game}:${env.SCORE_SALT}`),name=account?account.name:cleanName(b.name);if(!await allow(env,key))return json({error:'Too many submissions. Try again shortly.'},429,h);const old=await env.ARCADE_DB.prepare('SELECT id,score,duration FROM scores WHERE game=? AND player_hash=? ORDER BY score DESC,duration ASC LIMIT 1').bind(b.game,key).first(),improved=!old||score>Number(old.score)||(score===Number(old.score)&&duration<Number(old.duration));if(!old)await env.ARCADE_DB.prepare('INSERT INTO scores(game,name,score,level,duration,player_hash)VALUES(?,?,?,?,?,?)').bind(b.game,name,score,level,duration,key).run();else if(improved)await env.ARCADE_DB.prepare('UPDATE scores SET name=?,score=?,level=?,duration=?,created_at=CURRENT_TIMESTAMP WHERE id=?').bind(name,score,level,duration,old.id).run();const personalBest=improved?score:Number(old.score);return json({ok:true,improved,personalBest,rank:await rank(env,b.game,personalBest),synced:Boolean(account),game:b.game,scores:await scores(env,b.game)},old?200:201,h)}
async function health(request,env){const h=responseHeaders(request,env);try{const s=await env.ARCADE_DB.prepare('SELECT COUNT(*) records,COUNT(DISTINCT player_hash) players FROM scores').first(),a=await env.ARCADE_DB.prepare('SELECT COUNT(*) total FROM players').first();return json({ok:true,service:'grei-arcade-api',database:'connected',leaderboard:Boolean(env.SCORE_SALT),crossDeviceProfiles:true,accounts:Number(a?.total||0),records:Number(s?.records||0),players:Number(s?.players||0),games:Object.keys(GAME_RULES)},200,h)}catch{return json({ok:false,database:'unavailable',leaderboard:false},503,h)}}
export default{async fetch(request,env){const url=new URL(request.url),h=responseHeaders(request,env);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:h});if(url.pathname==='/api/profile')return profile(request,env);if(url.pathname==='/api/leaderboard')return leaderboard(request,env,url);if(url.pathname==='/api/health')return health(request,env);return json({error:'Not found.'},404,h)}};
